//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONDATHANG_MATHANG
    {
        public int MADDH { get; set; }
        public string MAMH { get; set; }
        public int SOLUONG { get; set; }
        public double DONGIA { get; set; }
    
        public virtual DON_DAT_HANG DON_DAT_HANG { get; set; }
        public virtual MAT_HANG MAT_HANG { get; set; }
    }
}
