//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.HOADON_MATHANG = new HashSet<HOADON_MATHANG>();
        }
    
        public int MAHOADON { get; set; }
        public System.DateTime NGAYLAP { get; set; }
        public string MANHANVIEN { get; set; }
        public Nullable<int> MAKH { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON_MATHANG> HOADON_MATHANG { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
    }
}
