//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON_MATHANG
    {
        public int MAHD { get; set; }
        public string MAMH { get; set; }
        public int SOLUONGMUA { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual HOA_DON HOA_DON { get; set; }
        public virtual MAT_HANG MAT_HANG { get; set; }
    }
}
